version: "3"
services:
  certbot:
    env_file: .env
    image: certbot/certbot:latest
    restart: "no"
    volumes:
      - "./.etc/certbot:/etc/letsencrypt"
    ports:
      - "80:80"
    command: "certonly -n --standalone --agree-tos --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN}"
  mediaproxy:
    build: ./mediaproxy
    restart: always
    expose:
      - 80
    networks:
      - media
  oauth:
    env_file: .env
    build: ./oauth
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./.etc/certbot:/etc/letsencrypt"
    networks:
      - media
    command: >
      oauth2_proxy
      --upstream="http://mediaproxy"
      --http-address="https://:443"
      --email-domain="${OAUTH2_PROXY_EMAIL_DOMAIN}"
      --tls-key="/etc/letsencrypt/live/${CERTBOT_DOMAIN}/privkey.pem"
      --tls-cert="/etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem"
  nzbget:
    image: linuxserver/nzbget:testing
    restart: always
    volumes:
      - "./.etc/nzbget/nzbget.conf:/config/nzbget.conf"
      - "./.downloads:/downloads"
    expose:
      - 6789
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
    networks:
      - media
  sickrage:
    image: xataz/sickrage:latest
    restart: always
    volumes:
      - "./sickrage-post.sh:/usr/bin/sickrage-post.sh:ro"
      - "./.etc/sickrage:/config"
      - "./.downloads:/downloads"
      - "./.downloads:/drive"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 8081
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
      WEBROOT: /tv
    networks:
      - media
  couchpotato:
    image: linuxserver/couchpotato:latest
    restart: always
    volumes:
      - "./.etc/couchpotato:/config"
      - "./.downloads:/downloads"
      - "./.downloads:/drive:shared"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 5050
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
    networks:
      - media

networks:
  media:
