version: "3"
services:
  certbot:
    env_file: .env
    image: certbot/certbot:latest
    restart: "no"
    volumes:
      - "./.etc/certbot:/etc/letsencrypt"
    ports:
      - "80:80"
    command: "certonly -n --standalone --agree-tos --email ${CERTBOT_EMAIL} -d ${CERTBOT_DOMAIN}"
  mediaproxy:
    build: ./mediaproxy
    restart: always
    expose:
      - 80
    networks:
      - media
  oauth:
    env_file: .env
    build: ./oauth
    restart: always
    ports:
      - "443:443"
    volumes:
      - "./.etc/certbot:/etc/letsencrypt"
    networks:
      - media
    command: >
      oauth2_proxy
      --upstream="http://mediaproxy"
      --http-address="https://:443"
      --email-domain="${OAUTH2_PROXY_EMAIL_DOMAIN}"
      --tls-key="/etc/letsencrypt/live/${CERTBOT_DOMAIN}/privkey.pem"
      --tls-cert="/etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem"
  nzbget:
    image: linuxserver/nzbget:testing
    restart: always
    volumes:
      - "./.etc/nzbget/nzbget.conf:/config/nzbget.conf"
      - "./.downloads:/downloads"
    expose:
      - 6789
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
    networks:
      - media
  sickrage:
    image: xataz/sickrage:latest
    restart: always
    volumes:
      - "./sickrage-post.sh:/usr/bin/sickrage-post.sh:ro"
      - "./.etc/sickrage:/config"
      - "./.downloads:/downloads"
      - "./.downloads:/drive"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 8081
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
      WEBROOT: /tv
    networks:
      - media
  couchpotato:
    image: linuxserver/couchpotato:latest
    restart: always
    volumes:
      - "./cp-post.sh:/usr/bin/cp-post.sh:ro"
      - "./.etc/couchpotato:/config"
      - "./.downloads:/downloads"
      - "./.downloads:/drive:shared"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 5050
    environment:
      PUID: 0
      GID: 0
      TZ: UTC
    networks:
      - media
  rclone:
    env_file: .env
    build: ./rclone
    restart: always
    security_opt:
      - 'apparmor:unconfined'
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - "./.cache/rclone:/cache"
      - "./.cache/upload:/upload"
      - "./.drive:/drive:shared"
      - "./.etc/rclone:/root/.config/rclone"
    command: >
      rclone mount 
        --log-level INFO 
        --allow-non-empty 
        --allow-other 
        --no-modtime 
        --checkers=4
        --cache-workers=2
        --cache-db-path=/cache 
        --cache-chunk-size=64M 
        --cache-total-chunk-size=40G 
        --cache-chunk-clean-interval=1m 
        --cache-info-age=48h 
        --cache-read-retries=10 
        --cache-workers=4 
        --cache-tmp-wait-time=15m 
        --cache-db-wait-time=1s 
        --cache-tmp-upload-path=/upload 
        drive-cache: /drive
  plex:
    env_file: .env
    image: plexinc/pms-docker:plexpass
    network_mode: host
    environment:
      TZ: PST8PDT
      PLEX_UID: 0
      PLEX_GID: 0
    volumes:
      - "./.etc/plex:/config"
      - "./.tmp/transcode:/transcode"
      - "./.drive:/drive:shared"
  tautulli:
    image: tautulli/tautulli:latest
    environment:
      PUID: 0
      GUID: 0
      ADVENCED_GIT_BRANCH: nightly
      TZ: PST8PDT
      PLEX_CLAIM: claim-5ZKsfko7q6W31KhUXJPq
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./.etc/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
      - "./.etc/plexpy:/config"
    expose:
      - 8181
    networks:
      - media
  netdata:
    image: titpetric/netdata:latest
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
    expose:
      - 19999
    networks:
      - media
  mylar:
    image: linuxserver/mylar:latest
    environment:
      PGID: 0
      PUID: 0
      TZ: PST8PDT
    expose:
      - 8090
    networks:
      - media
    volumes:
      - "./.etc/mylar:/config"
      - "./.downloads/Comics:/downloads"
      - "./.drive:/drive:shared"




networks:
  media:
