version: "3"
services:
  mediaproxy:
    build: ./mediaproxy
    restart: always
    expose:
      - 80
    networks:
      - media
  oauth:
    env_file: .env
    build: ./oauth
    restart: always
    ports:
    - "80:80"
    volumes:
      - "./.etc/certbot:/etc/letsencrypt"
    networks:
      - media
    command: >
      oauth2_proxy
      --upstream="http://mediaproxy"
      --http-address="http://:80"
      --email-domain="${OAUTH2_PROXY_EMAIL_DOMAIN}"
  nzbget:
    image: linuxserver/nzbget:testing
    restart: always
    volumes:
      - "./.etc/nzbget/nzbget.conf:/config/nzbget.conf"
      - "./.cache/downloads:/downloads"
    expose:
      - 6789
    environment:
      PUID: 0
      GID: 0
      TZ: PST8PDT
    networks:
      - media
  sickrage:
    image: xataz/sickrage:latest
    restart: always
    volumes:
      - "./sickrage-post.sh:/usr/bin/sickrage-post.sh:ro"
      - "./.etc/sickrage:/config"
      - "./.cache/downloads:/downloads"
      - "./.drive:/drive/Video:shared"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 8081
    environment:
      PUID: 0
      GID: 0
      TZ: PST8PDT
      WEBROOT: /tv
    depends_on:
      - rclone
    networks:
      - media
  couchpotato:
    image: linuxserver/couchpotato:latest
    restart: always
    volumes:
      - "./cp-post.sh:/usr/bin/cp-post.sh:ro"
      - "./.etc/couchpotato:/config"
      - "./.cache/downloads:/downloads"
      - "./.drive:/drive:shared"
      - "./.etc/rclone:/root/.config/rclone"
    expose:
      - 5050
    environment:
      PUID: 0
      GID: 0
      TZ: PST8PDT
    depends_on:
      - rclone
    networks:
      - media
  rclone:
    env_file: .env
    build: ./rclone
    restart: always
    networks:
      - media
    security_opt:
      - 'apparmor:unconfined'
    cap_add:
      - MKNOD
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - "./.cache/rclone:/cache"
      - "./.cache/upload:/upload"
      - "./.drive:/drive:shared"
      - "./.etc/rclone:/root/.config/rclone"
    command: >
      rclone mount 
        --log-level INFO
        --allow-non-empty 
        --allow-other 
        --no-modtime 
        --checkers=4
        --cache-dir=/cache
        --cache-db-path=/cache 
        --cache-db-wait-time=1s 
        --cache-chunk-path=/cache
        --cache-chunk-size=64M 
        --cache-chunk-total-size=40G 
        --cache-chunk-clean-interval=1m 
        --cache-info-age=12h 
        --cache-read-retries=10 
        --cache-workers=8 
        --cache-tmp-wait-time=15m 
        --cache-tmp-upload-path=/upload 
        --drive-use-created-date
        --drive-use-trash=false
        drive-cache: /drive
  plex:
    env_file: .env
    image: plexinc/pms-docker:plexpass
    networks:
      - media
    ports:
      - "8443:32400"
    expose:
      - 32400/tcp
      - 3005/tcp
      - 8324/tcp
      - 32469/tcp
      - 1900/udp
      - 32410/udp
      - 32412/udp
      - 32413/udp
      - 32414/udp
    depends_on:
      - rclone
    environment:
      TZ: PST8PDT
      PLEX_UID: 0
      PLEX_GID: 0
      CHANGE_CONFIG_DIR_OWNERSHIP: "false"
    volumes:
      - "./.etc/plex:/config"
      - "./.cache/transcode:/transcode"
      - "./.drive:/drive:shared"
  plexpy:
    image: tautulli/tautulli:latest
    environment:
      PUID: 0
      GUID: 0
      ADVANCED_GIT_BRANCH: nightly
      TZ: PST8PDT
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./.etc/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
      - "./.etc/plexpy:/config"
    expose:
      - 8181
    networks:
      - media
  books:
    image: linuxserver/ubooquity:latest
    environment:
      PUID: 0
      GUID: 0
      TZ: PST8PDT
      MAXMEM: 1500
    volumes:
      - "./.etc/ubooquity:/config"
      - "./.cache/downloads:/downloads"
      - "./.drive:/drive:shared"
    expose:
      - 2202
      - 2203
    networks:
      - media

networks:
  media:
